version: '3.9'

services:

  db:
      image: postgres
      ports:
        - "5432:5432"  # dev exposure
      volumes:
        - ./data/db:/var/lib/postgresql/data
      env_file:
        - .env.postgres

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - 'redis_data:/var/lib/redis/data'

  web:
    build: ./web
    command: ["./init.sh"]
    volumes:
      - ./web:/web
      - ./data/outputs:/outputs
    ports:
      - "8000:8000"
    env_file:
      - .env.postgres
      - .env.django
    environment:
      PORT: "8000"
      DJANGO_BACKEND_WORKER: "True"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis

volumes:
  redis_data:
